SOCIALMEDIA/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('administration/',include('administration.urls'))
]

administration/urls.py
from django.urls import path
from . import views
app_name = "administration"
urlpatterns = [
    path('home', views.index,name='quotespage'),
    path('log_out/',views.logout, name = 'logout'),
    path('approve/<int:uid>',views.approve, name = 'approve'),


   
]

user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('', views.index,name='signup'),
    path('home', views.homepage,name='homepage'),
    path('userlogin', views.login_user,name='loginuser'),
    path('log_out/',views.logout, name = 'logout'),
    path('quote', views.quote,name='quote'),
    path('viewquote', views.view_quote,name='viewquote'),


   
]

administration/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models


# Create your models here.

class Userdetails(models.Model):
    name = models.CharField(max_length=20,default='')

class Authentication(models.Model):
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=10)
    role = models.CharField(max_length=10,default="user") 
    user = models.ForeignKey(Userdetails,on_delete=models.CASCADE)

class Quotes(models.Model):
    user = models.ForeignKey(Userdetails,on_delete=models.CASCADE,default='')
    status = models.CharField(max_length=50,default='pending')
    quote = models.CharField(max_length=1000)

administration/views.py
from django.shortcuts import render,redirect

from user.models import Quotes

# Create your views here.
def index(request):
    quotes = Quotes.objects.all()
    
    return render (request,'admin/quotespage.html',{'quotesList' : quotes})

def logout(request) :
    del request.session['admin_id']
    return redirect('user:loginuser')

def approve(request,uid):
    quotes = Quotes.objects.all()
    data = Quotes.objects.filter(id = uid)
    data.update(status='approve')
    return render (request,'admin/quotespage.html',{'quotesList' : quotes})

user/views.py
from django.shortcuts import render,redirect
from user.models import Authentication, Quotes, Userdetails



# Create your views here.
def index(request):
    if request.method == 'POST':
        name = request.POST['yourname']
        username = request.POST['username']
        password = request.POST['password']
        user1 = Userdetails(
            name = name
        )
        user1.save()
        print(user1.id)
        common = Authentication(
            username = username,
            password = password,
            user_id =user1.id
        )
        common.save()

    return render (request,'user/signup.html')



def homepage(request):
    return render (request,'user/home.html')

def login_user(request):
    msg = ""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try :
                user = Authentication.objects.get(
                username = username,
                password = password
                )

                if user.role == 'admin':
                    request.session['admin_id']=user.id 
                    return redirect('administration:quotespage')
                elif user.role == 'user':
                    request.session['user_id']=user.id
                    return redirect('user:quote')
        except : 
                msg = 'invalid username or password'
            
                
    return render (request,'user/login_user.html',{'error_msg':msg})

def logout(request) :
    del request.session['user_id']
    return redirect('user:loginuser')


def quote(request):
    if request.method == 'POST':
        new_quote = request.POST['creating_quote']
        quote1 = Quotes(
            user_id =  request.session['user_id'],
            quote = new_quote
        )
        quote1.save()        
    return render (request,'user/quote.html')


def view_quote(request):
    new_quote = Quotes.objects.all()
    return render (request,'user/viewquote.html',{'quotesList' : new_quote})

user/templates/user/dh.html
<script>
    $(document).ready(function(){
      $('#signup_form').validate({
        rules : {
            yourname : {
              required : true,
              minlength : 4
            },
            username : {
              required : true,
              minlength : 5
            },
            password : {
              required : true,
              minlength : 5
            },
            confirm_password : {
              required : true,
              equalto : 'password'
            }
        },
        messages : {
            yourname : {
              required : 'Please Enter your Name ',
              minlength : 'Required Minimum four letters'
            },
            username : {
              required : 'Please Enter a username',
              minlength : 'Required Minimum five letters'
            },
            confirm_password : {
              required : 'Please confirm the password',
              equalto : 'Password not matching'
            }
        }
      })
    })
  </script>

user/templates/user/extension.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
  </head>
  {% block content %}

  {% endblock %}
  <body>
    <div class="container">
        <div class="row mt-3 ml-2">
            <div class="col-md-3 left">
                
                <div class="p-4 pt-5">
                  <a href="{% url 'user:viewquote' %}"><h2>View Quotes</h2></a>
                  <a href="{% url 'user:quote' %}"><h2>Post Your Quotes</h2></a>
                  <a href="{% url 'user:logout' %}"><h2>LOG-OUT</h2></a>

                  </div>
                
            </div>
            <div class="col-md-9 right">
                {% block right_content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/home.html
{% extends 'user/extension.html' %}

{% load static %}
{% block left_content %}
<div class="p-4 pt-5">
<a href=""><h2>View Quotes</h2></a>
<a href=""><h2>Post Your Quotes</h2></a>
</div>
{% endblock %}

{% block right_content %}
<div class="p-4 pt-5">
    
</div>
{% endblock %}

user/templates/user/login_user.html
{% extends 'user/masterpage.html' %}

{% load static %}
{% block content %}
<section>
    <section class="vh-100" style="background-color: #508bfc;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
      
                  <h3 class="mb-5">SIGN IN AS USER/ADMIN</h3>
                  {{ error_msg }}
                  <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-outline mb-4">
                    <input type="text" id="typeEmailX-2" class="form-control form-control-lg" name="username">
                    <label class="form-label" for="typeEmailX-2">USERNAME</label>
                  </div>
      
                  <div class="form-outline mb-4">
                    <input type="password" id="typePasswordX-2" class="form-control form-control-lg" name="password">
                    <label class="form-label" for="typePasswordX-2">Password</label>
                  </div>
                  <select class="form-select" hidden aria-label="Default select example" name="role">
                    <option selected value="user">User</option>
                    <option value="1" value="Admin">Admin</option>
                  </select>
                  <button class="btn btn-primary  " type="submit">Login</button>
                </form>
                  <hr class="my-4">
      
                  
      
      
                  
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</section>
{% endblock %}

user/templates/user/masterpage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
  </head>
  {% block header %}

  {% endblock %}
  <body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5"></div>
            <div class="col-md-6">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'user:signup' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:loginuser' %}">USER LOGIN</a>
                          </li>

                        </ul>
                      </div>
                    </div>
                  </nav>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>


  {% block content %}

  {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/quote.html
{% extends 'user/extension.html' %}

{% load static %}


{% block right_content %}
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="p-4 pt-5">
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label"></label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="15" placeholder="Enter your post here..." name="creating_quote"></textarea>
      </div>
      <div class="text-center">
      <button class="btn btn-primary w-50" type="submit">CREATE POST</button>
    </div>
</div>
</form>
{% endblock %}

user/templates/user/signup.html
{% extends 'user/masterpage.html' %}

{% load static %}
{% block content %}
<section>
  <style>
    .error{
      color: red;
    }
  </style>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form class="mx-1 mx-md-4" id="signup_form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example1c">Your Name</label>
                            <input type="text"  class="form-control" placeholder="Enter Your Name" id="yourname" name="yourname">
                            <span id="name_error"></span>
                          </div>
                        </div>
                        <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" for="form3Example1c">Username</label>
                              <input type="text"  class="form-control" placeholder="Enter Username" id="username" name="username">
                              <span id="username_error"></span>
                            </div>
                          </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example4c">Password</label>
                            <input type="password" id="password" class="form-control" placeholder="Enter Password" name="password">
                            <span id="password_error"></span>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example4cd">Confirm your password</label>
                            <input type="password" id="confirmpassword" class="form-control"  placeholder="Enter Confirm Password" name="confirm_password">
                            <span id="cofmpswd_error"></span>
                          </div>
                        </div>
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg" id="submit" onclick="return valdate()">Register</button>
                        </div>
 
                      </form>
      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</section>

<!-- <script>
  function valdate(){
  var yourname = document.getElementById('yourname')
  var username = document.getElementById('username')
  var pswd = document.getElementById('password')
  var conf_pswd = document.getElementById('confirmpassword') 

  if(yourname.value == ""){
    yourname.style.border = '1px solid red'
    name_error.innerHTML = 'Enter your Name'
    name_error.style.color = 'red'
  return false
  }
  else{
    name_error.innerHTML = ""
  }
  if(yourname.value.length <=4){
    name_error.innerHTML = ' Should contain minimum length of four '
    name_error.style.color = 'red'
    return false
  }
  else{
    name_error.innerHTML = ""
  }

  ///////////////////////////////////////////////

  if(username.value == ""){
    username.style.border = '1px solid red'
    username_error.innerHTML = 'Enter your Name'
    username_error.style.color = 'red'
  return false
  }
  else{
    username_error.innerHTML = ""
  }
  if(username.value.length <=5){
    username_error.innerHTML = ' Should contain minimum length of five '
    username_error.style.color = 'red'
    return false
  }
  else{
    username_error.innerHTML = ""
  }
  ////////////////////////
  if(pswd.value == ""){
    pswd.style.border = '1px solid red'
    password_error.innerHTML = 'This space is to be filled'
    password_error.style.color = 'red'
  return false
  }
  else{
    password_error.innerHTML = ""
  }
  if(pswd.value.length <=5){
    password_error.innerHTML = ' Should contain minimum length of five '
    password_error.style.color = 'red'
    return false
  }
  else{
    password_error.innerHTML = ""
  }


//////////////////////////////

//////////////////////////////

  if(conf_pswd.value == ""){
    conf_pswd.style.border = '1px solid red'
    cofmpswd_error.innerHTML = 'This space is to be filled'
    cofmpswd_error.style.color = 'red'
  return false
  }
  else{
    password_error.innerHTML = ""
  }
  if(pswd.value != conf_pswd.value){
    cofmpswd_error.innerHTML = ' Password not matching '
    cofmpswd_error.style.color = 'red'
    return false
  }
  else{
    cofmpswd_error.innerHTML = ""
  }
  }
</script> -->




<script>
  $(document).ready(function(){
    $('#signup_form').validate({
      rules : {
          yourname : {
            required : true,
            minlength : 4
          },
          username : {
            required : true,
            minlength : 5
          },
          password : {
            required : true,
            minlength : 5
          },
          confirm_password : {
            required : true,
            equalTo : password
          }
      },

      messages : {
          yourname : {
            required : 'Please Enter your Name ',
            minlength : 'Required Minimum four letters'
          },
          username : {
            required : 'Please Enter a username',
            minlength : 'Required Minimum five letters'
          },
          confirm_password : {
            required : 'Please confirm the password',
            equalto : 'Password not matching'
            
          }
      }
     
    })
  })
</script>
{% endblock %}

user/templates/user/viewquote.html
{% extends 'user/extension.html' %}

{% load static %}

{% block right_content %}
<style>
.text{
  background-color: white;
  height: 100%;
  width: 80%;
  margin: 2%;
  padding: 5%;
}
</style>
<div class="p-4 pt-5">
      <div class="mb-3">
      {% for quote in quotesList %}
      {% if quote.status == 'approve' %}
      <div class="text">
        <h4>{{quote.user.name}}</h4>
        <p>{{quote.quote}}</p>
      </div>
      {% endif %}
      {% endfor %}

      </div>
</div>
{% endblock %}